/**
 * Short abbreviations for blob poster names (2-4 characters)
 */
const SHORT_NAME_MAP: Record<string, string> = {
  abstract: 'ABS',
  aevo: 'AEVO',
  arbitrum: 'ARB',
  'arbitrum one': 'ARB',
  'arena-z': 'ARNZ',
  aztec: 'AZT',
  base: 'BASE',
  binary: 'BIN',
  blast: 'BLST',
  bob: 'BOB',
  'bob network': 'BOB',
  boba: 'BOBA',
  'boba network': 'BOBA',
  codex: 'CDX',
  debank: 'DBK',
  'debank chain': 'DBK',
  ethernity: 'ERN',
  forknet: 'FORK',
  fuel: 'FUEL',
  hashkey: 'HKEY',
  hemi: 'HEMI',
  ink: 'INK',
  jovay: 'JVY',
  katana: 'KTN',
  kinto: 'KTO',
  kroma: 'KROM',
  lachain: 'LA',
  lambda: 'LMDA',
  lighter: 'LGHT',
  linea: 'LNA',
  lisk: 'LSK',
  lumio: 'LUM',
  mantle: 'MNT',
  metal: 'MTL',
  metis: 'MTS',
  mint: 'MINT',
  mode: 'MODE',
  morph: 'MRPH',
  nanon: 'NAN',
  'nanon network': 'NAN',
  'op mainnet': 'OP',
  optimism: 'OP',
  opbnb: 'OPNB',
  optopia: 'OPTA',
  orderly: 'ORDR',
  phala: 'PHA',
  'phala network': 'PHA',
  pk910: 'PK',
  polynomial: 'POLY',
  r0ar: 'R0AR',
  'r0ar chain': 'R0AR',
  race: 'RACE',
  redstone: 'RSTM',
  scroll: 'SCRL',
  shape: 'SHPE',
  snaxchain: 'SNAX',
  soneium: 'SONM',
  soon: 'SOON',
  spire: 'SPIR',
  'spire da builder': 'SPIR',
  superseed: 'SSED',
  swan: 'SWAN',
  'swan chain': 'SWAN',
  swell: 'SWEL',
  taiko: 'TAKO',
  unichain: 'UNI',
  world: 'WRLD',
  'world chain': 'WRLD',
  xterio: 'XTER',
  zero: 'ZERO',
  'zero network': 'ZERO',
  'zerϴ network': 'ZERO',
  zircuit: 'ZIRC',
  zksync: 'ZKS',
  'zksync era': 'ZKS',
  'zksync gateway': 'ZKGW',
  zora: 'ZORA',
  unknown: 'UNKNOWN',
};

/**
 * Get short abbreviation for a blob poster name
 */
export function getBlobPosterShortName(posterName: string): string {
  const normalized = posterName.toLowerCase().trim();
  return SHORT_NAME_MAP[normalized] ?? posterName.slice(0, 4).toUpperCase();
}
