export interface BlobPosterLogoProps {
  /**
   * Blob poster name (L2 network name, e.g., "arbitrum", "base", "optimism")
   */
  poster: string;
  /**
   * Size of the logo in pixels (default: 20px)
   */
  size?: number;
  /**
   * Additional CSS classes
   */
  className?: string;
}

/**
 * Mapping from normalized names to API display names.
 * The API returns proper-cased names that must match exactly for filtering.
 */
export const BLOB_POSTER_DISPLAY_NAMES: Record<string, string> = {
  abstract: 'Abstract',
  aevo: 'Aevo',
  arbitrum: 'Arbitrum One',
  'arena-z': 'Arena-Z',
  aztec: 'Aztec',
  base: 'Base',
  binary: 'Binary',
  blast: 'Blast',
  bob: 'BOB Network',
  boba: 'Boba Network',
  codex: 'Codex',
  debank: 'DeBank Chain',
  ethernity: 'Ethernity',
  forknet: 'Forknet',
  fuel: 'Fuel',
  hashkey: 'HashKey',
  hemi: 'Hemi',
  ink: 'Ink',
  jovay: 'Jovay',
  katana: 'Katana',
  kinto: 'Kinto',
  kroma: 'Kroma',
  lachain: 'LaChain',
  lambda: 'Lambda',
  lighter: 'Lighter',
  linea: 'Linea',
  lisk: 'Lisk',
  lumio: 'Lumio',
  mantle: 'Mantle',
  metal: 'Metal',
  metamail: 'MetaMail',
  metis: 'Metis',
  mint: 'Mint',
  mode: 'Mode',
  morph: 'Morph',
  nanon: 'Nanon Network',
  optimism: 'OP Mainnet',
  opbnb: 'opBNB',
  optopia: 'Optopia',
  orderly: 'Orderly',
  pandasea: 'PandaSea',
  paradex: 'Paradex',
  parallel: 'Parallel',
  phala: 'Phala Network',
  polynomial: 'Polynomial',
  r0ar: 'R0AR Chain',
  race: 'Race',
  redstone: 'Redstone',
  river: 'River',
  scroll: 'Scroll',
  settlus: 'Settlus',
  shape: 'Shape',
  snaxchain: 'Snaxchain',
  soneium: 'Soneium',
  soon: 'Soon',
  spire: 'Spire DA Builder',
  starknet: 'Starknet',
  superseed: 'Superseed',
  swan: 'Swan Chain',
  swell: 'Swell',
  swellchain: 'Swellchain',
  symbiosis: 'Symbiosis',
  taiko: 'Taiko',
  unichain: 'Unichain',
  world: 'World Chain',
  xga: 'XGA',
  xlayer: 'XLayer',
  xterio: 'Xterio',
  zero: 'Zerϴ Network',
  zircuit: 'Zircuit',
  zksync: 'zkSync Era',
  'zksync-gateway': 'zkSync Gateway',
  zora: 'ZORA',
};

/**
 * List of known blob poster (L2) networks (normalized lowercase names for image paths)
 */
export const BLOB_POSTERS = [
  'abstract',
  'aevo',
  'arbitrum',
  'arena-z',
  'aztec',
  'base',
  'binary',
  'blast',
  'bob',
  'boba',
  'codex',
  'debank',
  'ethernity',
  'forknet',
  'fuel',
  'hashkey',
  'hemi',
  'ink',
  'jovay',
  'katana',
  'kinto',
  'kroma',
  'lachain',
  'lambda',
  'lighter',
  'linea',
  'lisk',
  'lumio',
  'mantle',
  'metal',
  'metamail',
  'metis',
  'mint',
  'mode',
  'morph',
  'nanon',
  'optimism',
  'optopia',
  'pandasea',
  'paradex',
  'parallel',
  'phala',
  'polynomial',
  'r0ar',
  'race',
  'river',
  'scroll',
  'settlus',
  'shape',
  'snaxchain',
  'soneium',
  'spire',
  'starknet',
  'superseed',
  'swan',
  'swell',
  'swellchain',
  'symbiosis',
  'taiko',
  'unichain',
  'world',
  'xga',
  'xlayer',
  'zero',
  'zircuit',
  'zksync',
  'zksync-gateway',
  'zora',
] as const;

export type BlobPoster = (typeof BLOB_POSTERS)[number];
