data:
  type: fs
  path: ../data # pwd is ./notebooks
notebooks:
  xatu-public-contributors:
    enabled: true
    schedule_hours: 1
    description: "Analyzes public Xatu contributor data and client versions"
    networks:
      - mainnet
      - sepolia
      - holesky
    time_windows:
      - file: "last_90_days"
        step: "3d"
        label: "Last 90d" 
        range: "-90d"
      - file: "last_30_days" 
        step: "1d"
        label: "Last 30d"
        range: "-30d"
      - file: "last_1_day"
        step: "1h" 
        label: "Last 1d"
        range: "-1d"
      - file: "last_6h"
        step: "5m" 
        label: "Last 6h"
        range: "-6h"
  # mev-relays:
  #   enabled: false
  #   schedule_hours: 1
  #   description: "Analyzes MEV relays"
  #   networks:
  #     - mainnet
  beacon-chain-timings:
    enabled: true
    schedule_hours: 1
    description: "Analyzes beacon chain timings"
    networks:
      - mainnet
      - sepolia
      - holesky
    time_windows:
      - file: "last_30_days" 
        step: "6h"
        label: "Last 30d"
        range: "-30d"
      - file: "last_90_days"
        step: "1d"
        label: "Last 90d" 
        range: "-90d"
      # - file: "last_1_day"
      #   step: "5m" 
      #   label: "Last 1d"
      #   range: "-1d"
      # - file: "last_year"
      #   step: "1d" 
      #   label: "Last 1y"
      #   range: "-365d"