version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - redis_data:/data
    profiles: 
      - '*'
      - infra

  minio:
    image: minio/minio
    command: server /data --console-address ":9001" --anonymous
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    profiles: 
      - '*'
      - infra

  # Create the lab bucket in MinIO
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/lab;
      /usr/bin/mc policy set public myminio/lab;
      exit 0;
      "
    profiles: 
      - '*'
      - infra

  server:
    build:
      context: .
      dockerfile: Dockerfile.golang
    command: ["srv", "--srv-config", "/app/config/service.config.yaml"]
    environment:
      - XATU_CLICKHOUSE_USERNAME=${XATU_CLICKHOUSE_USERNAME}
      - XATU_CLICKHOUSE_PASSWORD=${XATU_CLICKHOUSE_PASSWORD}
    ports:
      - "6666:6666"
    volumes:
      - ./deploy/docker-compose/service.config.yaml:/app/config/service.config.yaml
    profiles: 
      - 'backend'

  api:
    build:
      context: .
      dockerfile: Dockerfile.golang
    environment:
      - SRV_ADDRESS=${SRV_ADDRESS:-server:6666}
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-8080}
      - S3_ENDPOINT=${S3_ENDPOINT:-minio:9000}
      - S3_REGION=${S3_REGION:-us-east-1}
      - S3_BUCKET=${S3_BUCKET:-lab}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-minioadmin}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-minioadmin}
      - REDIS_URL=${REDIS_URL:-redis:6379}
    command: ["api", "--api-config", "/app/config/api.config.yaml"]
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ./deploy/docker-compose/api.config.yaml:/app/config/api.config.yaml
    profiles: 
      - 'backend'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      VITE_BACKEND_URL: http://api:8080
    profiles: 
      - 'frontend'

volumes:
  minio_data:
  redis_data: