storage:
  s3:
    endpoint: "https://s3.example.com"
    region: "us-east-1"
    bucket: "lab-data"
    access_key_id: "your-access-key"
    secret_access_key: "your-secret-key"

clickhouse:
  url: "http://localhost:8123"
  database: "default"
  username: "default"
  password: ""
  debug: false

modules:
  beacon_chain_timings:
    enabled: false
    description: "Beacon chain block timing metrics and analysis"
    path_prefix: "beacon_chain_timings"
    networks:
      - mainnet
      - sepolia
      - holesky
    time_windows:
      - file: last_30_days
        step: 6h
        label: Last 30d
        range: -720h # 30 days
      - file: last_60_days
        step: 6h
        label: Last 60d
        range: -1440h # 60 days
      - file: last_90_days
        step: 24h
        label: Last 90d
        range: -2160h # 90 days
    interval: 1h 
  xatu_public_contributors:
    enabled: true
    description: "Xatu public contributor metrics and analysis"
    path_prefix: "xatu_public_contributors"
    schedule_hours: 1
    networks:
      - mainnet
      - sepolia
      - holesky
    time_windows:
      - file: "last_90_days"
        step: "3d"
        label: "Last 90d" 
        range: "-90d"
      - file: "last_30_days" 
        step: "1d"
        label: "Last 30d"
        range: "-30d"
      - file: "last_1_day"
        step: "1h" 
        label: "Last 1d"
        range: "-1d"
      - file: "last_6h"
        step: "5m" 
        label: "Last 6h"
        range: "-6h"