storage:
#   s3:
#     endpoint: "http://localhost:9000"
#     region: "us-east-1"
#     bucket: "lab-data"
#     access_key_id: "minioadmin"
#     secret_access_key: "minioadmin"
  s3:
    access_key_id: 59c82054d65cf2376eeac913570cd1f9
    bucket: "ethpandaops-platform-staging-lab-data"
    endpoint: https://539bc53131934672bf85e7260ec0b218.r2.cloudflarestorage.com
    region: eeur
    secret_access_key: 171c4fae06b80555e3187d3ace8d2c38a3889b1c613294dff2d95a95102eebf9

# clickhouse:
#   url: "clickhouse+http://pandaops:89de7199-392d-4000-a96f-bd4e712d303a@clickhouse.xatu.ethpandaops.io:443/default?protocol=https"
clickhouse:
  url: clickhouse+http://lab:86e30815-488b-4e22-b203-5eec220b7b80@chproxy.analytics.staging.platform.ethpandaops.io:443/default?protocol=https


modules:
  beacon_chain_timings:
    enabled: true
    description: "Beacon chain block timing metrics and analysis"
    path_prefix: "beacon_chain_timings"
    networks:
      - mainnet
      - sepolia
      - holesky
    time_windows:
      - file: last_30_days
        step: 6h
        label: Last 30d
        range: -720h # 30 days
      - file: last_60_days
        step: 6h
        label: Last 60d
        range: -1440h # 60 days
      - file: last_90_days
        step: 24h
        label: Last 90d
        range: -2160h # 90 days
    interval: 1h 
  xatu_public_contributors:
    enabled: true
    description: "Xatu public contributor metrics and analysis"
    path_prefix: "xatu_public_contributors"
    schedule_hours: 1
    networks:
      - mainnet
      - sepolia
      - holesky
    time_windows:
      - file: "last_90_days"
        step: "3d"
        label: "Last 90d" 
        range: "-90d"
      - file: "last_30_days" 
        step: "1d"
        label: "Last 30d"
        range: "-30d"
      - file: "last_1_day"
        step: "1h" 
        label: "Last 1d"
        range: "-1d"
      - file: "last_6h"
        step: "5m" 
        label: "Last 6h"
        range: "-6h"