// Package models contains auto-generated Go structs for Xatu ClickHouse tables.
// DO NOT EDIT - Generated by generate_xatu_clickhouse_models.sh
package models

import (
    "time"
)

// CanonicalExecutionNonceDiffs represents a row from the canonical_execution_nonce_diffs table.
type CanonicalExecutionNonceDiffs struct {
    UpdatedDateTime    time.Time    `db:"updated_date_time" json:"updated_date_time"`
    BlockNumber    uint64    `db:"block_number" json:"block_number"`
    TransactionIndex    uint64    `db:"transaction_index" json:"transaction_index"`
    TransactionHash    string    `db:"transaction_hash" json:"transaction_hash"`
    InternalIndex    uint32    `db:"internal_index" json:"internal_index"`
    Address    string    `db:"address" json:"address"`
    FromValue    uint64    `db:"from_value" json:"from_value"`
    ToValue    uint64    `db:"to_value" json:"to_value"`
    MetaNetworkId    int32    `db:"meta_network_id" json:"meta_network_id"`
    MetaNetworkName    string    `db:"meta_network_name" json:"meta_network_name"`
}

// TableName returns the table name for CanonicalExecutionNonceDiffs.
func (m *CanonicalExecutionNonceDiffs) TableName() string {
    return "canonical_execution_nonce_diffs"
}

// CanonicalExecutionNonceDiffsParams represents query parameters for the canonical_execution_nonce_diffs table.
type CanonicalExecutionNonceDiffsParams struct {
    // Common query parameters
    Limit  *uint64
    Offset *uint64

    // Table-specific parameters based on columns
    // Add specific query parameters here as needed
}
