// Package models contains auto-generated Go structs for Xatu ClickHouse tables.
// DO NOT EDIT - Generated by generate_xatu_clickhouse_models.sh
package models

import (
    "time"
)

// CanonicalExecutionContracts represents a row from the canonical_execution_contracts table.
type CanonicalExecutionContracts struct {
    UpdatedDateTime    time.Time    `db:"updated_date_time" json:"updated_date_time"`
    BlockNumber    uint32    `db:"block_number" json:"block_number"`
    TransactionHash    string    `db:"transaction_hash" json:"transaction_hash"`
    InternalIndex    uint32    `db:"internal_index" json:"internal_index"`
    CreateIndex    uint32    `db:"create_index" json:"create_index"`
    ContractAddress    string    `db:"contract_address" json:"contract_address"`
    Deployer    string    `db:"deployer" json:"deployer"`
    Factory    string    `db:"factory" json:"factory"`
    InitCode    string    `db:"init_code" json:"init_code"`
    Code    *string    `db:"code" json:"code"`
    InitCodeHash    string    `db:"init_code_hash" json:"init_code_hash"`
    NInitCodeBytes    uint32    `db:"n_init_code_bytes" json:"n_init_code_bytes"`
    NCodeBytes    uint32    `db:"n_code_bytes" json:"n_code_bytes"`
    CodeHash    string    `db:"code_hash" json:"code_hash"`
    MetaNetworkId    int32    `db:"meta_network_id" json:"meta_network_id"`
    MetaNetworkName    string    `db:"meta_network_name" json:"meta_network_name"`
}

// TableName returns the table name for CanonicalExecutionContracts.
func (m *CanonicalExecutionContracts) TableName() string {
    return "canonical_execution_contracts"
}

// CanonicalExecutionContractsParams represents query parameters for the canonical_execution_contracts table.
type CanonicalExecutionContractsParams struct {
    // Common query parameters
    Limit  *uint64
    Offset *uint64

    // Table-specific parameters based on columns
    // Add specific query parameters here as needed
}
