// Package models contains auto-generated Go structs for Xatu ClickHouse tables.
// DO NOT EDIT - Generated by generate_xatu_clickhouse_models.sh
package models

import (
    "time"
)

// CanonicalExecutionLogs represents a row from the canonical_execution_logs table.
type CanonicalExecutionLogs struct {
    UpdatedDateTime    time.Time    `db:"updated_date_time" json:"updated_date_time"`
    BlockNumber    uint32    `db:"block_number" json:"block_number"`
    TransactionIndex    uint32    `db:"transaction_index" json:"transaction_index"`
    TransactionHash    string    `db:"transaction_hash" json:"transaction_hash"`
    InternalIndex    uint32    `db:"internal_index" json:"internal_index"`
    LogIndex    uint32    `db:"log_index" json:"log_index"`
    Address    string    `db:"address" json:"address"`
    Topic0    string    `db:"topic0" json:"topic0"`
    Topic1    *string    `db:"topic1" json:"topic1"`
    Topic2    *string    `db:"topic2" json:"topic2"`
    Topic3    *string    `db:"topic3" json:"topic3"`
    Data    *string    `db:"data" json:"data"`
    MetaNetworkId    int32    `db:"meta_network_id" json:"meta_network_id"`
    MetaNetworkName    string    `db:"meta_network_name" json:"meta_network_name"`
}

// TableName returns the table name for CanonicalExecutionLogs.
func (m *CanonicalExecutionLogs) TableName() string {
    return "canonical_execution_logs"
}

// CanonicalExecutionLogsParams represents query parameters for the canonical_execution_logs table.
type CanonicalExecutionLogsParams struct {
    // Common query parameters
    Limit  *uint64
    Offset *uint64

    // Table-specific parameters based on columns
    // Add specific query parameters here as needed
}
