// Package models contains auto-generated Go structs for Xatu ClickHouse tables.
// DO NOT EDIT - Generated by generate_xatu_clickhouse_models.sh
package models

import (
    "time"
)

// CanonicalBeaconBlockExecutionTransaction represents a row from the canonical_beacon_block_execution_transaction table.
type CanonicalBeaconBlockExecutionTransaction struct {
    UpdatedDateTime    time.Time    `db:"updated_date_time" json:"updated_date_time"`
    Slot    uint32    `db:"slot" json:"slot"`
    SlotStartDateTime    time.Time    `db:"slot_start_date_time" json:"slot_start_date_time"`
    Epoch    uint32    `db:"epoch" json:"epoch"`
    EpochStartDateTime    time.Time    `db:"epoch_start_date_time" json:"epoch_start_date_time"`
    BlockRoot    string    `db:"block_root" json:"block_root"`
    BlockVersion    string    `db:"block_version" json:"block_version"`
    Position    uint32    `db:"position" json:"position"`
    Hash    string    `db:"hash" json:"hash"`
    From    string    `db:"from" json:"from"`
    To    *string    `db:"to" json:"to"`
    Nonce    uint64    `db:"nonce" json:"nonce"`
    GasPrice    string    `db:"gas_price" json:"gas_price"`
    Gas    uint64    `db:"gas" json:"gas"`
    GasTipCap    *string    `db:"gas_tip_cap" json:"gas_tip_cap"`
    GasFeeCap    *string    `db:"gas_fee_cap" json:"gas_fee_cap"`
    Value    string    `db:"value" json:"value"`
    Type    uint32    `db:"type" json:"type"`
    Size    uint32    `db:"size" json:"size"`
    CallDataSize    uint32    `db:"call_data_size" json:"call_data_size"`
    BlobGas    *string    `db:"blob_gas" json:"blob_gas"`
    BlobGasFeeCap    *string    `db:"blob_gas_fee_cap" json:"blob_gas_fee_cap"`
    BlobHashes    []string    `db:"blob_hashes" json:"blob_hashes"`
    BlobSidecarsSize    *string    `db:"blob_sidecars_size" json:"blob_sidecars_size"`
    BlobSidecarsEmptySize    *string    `db:"blob_sidecars_empty_size" json:"blob_sidecars_empty_size"`
    MetaClientName    string    `db:"meta_client_name" json:"meta_client_name"`
    MetaClientId    string    `db:"meta_client_id" json:"meta_client_id"`
    MetaClientVersion    string    `db:"meta_client_version" json:"meta_client_version"`
    MetaClientImplementation    string    `db:"meta_client_implementation" json:"meta_client_implementation"`
    MetaClientOs    string    `db:"meta_client_os" json:"meta_client_os"`
    MetaClientIp    *string    `db:"meta_client_ip" json:"meta_client_ip"`
    MetaClientGeoCity    string    `db:"meta_client_geo_city" json:"meta_client_geo_city"`
    MetaClientGeoCountry    string    `db:"meta_client_geo_country" json:"meta_client_geo_country"`
    MetaClientGeoCountryCode    string    `db:"meta_client_geo_country_code" json:"meta_client_geo_country_code"`
    MetaClientGeoContinentCode    string    `db:"meta_client_geo_continent_code" json:"meta_client_geo_continent_code"`
    MetaClientGeoLongitude    *string    `db:"meta_client_geo_longitude" json:"meta_client_geo_longitude"`
    MetaClientGeoLatitude    *string    `db:"meta_client_geo_latitude" json:"meta_client_geo_latitude"`
    MetaClientGeoAutonomousSystemNumber    *string    `db:"meta_client_geo_autonomous_system_number" json:"meta_client_geo_autonomous_system_number"`
    MetaClientGeoAutonomousSystemOrganization    *string    `db:"meta_client_geo_autonomous_system_organization" json:"meta_client_geo_autonomous_system_organization"`
    MetaNetworkId    int32    `db:"meta_network_id" json:"meta_network_id"`
    MetaNetworkName    string    `db:"meta_network_name" json:"meta_network_name"`
    MetaConsensusVersion    string    `db:"meta_consensus_version" json:"meta_consensus_version"`
    MetaConsensusVersionMajor    string    `db:"meta_consensus_version_major" json:"meta_consensus_version_major"`
    MetaConsensusVersionMinor    string    `db:"meta_consensus_version_minor" json:"meta_consensus_version_minor"`
    MetaConsensusVersionPatch    string    `db:"meta_consensus_version_patch" json:"meta_consensus_version_patch"`
    MetaConsensusImplementation    string    `db:"meta_consensus_implementation" json:"meta_consensus_implementation"`
    MetaLabels    map[string]string    `db:"meta_labels" json:"meta_labels"`
}

// TableName returns the table name for CanonicalBeaconBlockExecutionTransaction.
func (m *CanonicalBeaconBlockExecutionTransaction) TableName() string {
    return "canonical_beacon_block_execution_transaction"
}

// CanonicalBeaconBlockExecutionTransactionParams represents query parameters for the canonical_beacon_block_execution_transaction table.
type CanonicalBeaconBlockExecutionTransactionParams struct {
    // Common query parameters
    Limit  *uint64
    Offset *uint64

    // Table-specific parameters based on columns
    // Add specific query parameters here as needed
}
