// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pkg/server/proto/xatu_public_contributors/xatu_public_contributors.proto

package xatu_public_contributors

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// XatuPublicContributorsServiceClient is the client API for XatuPublicContributorsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The xatu_public_contributors service definition
type XatuPublicContributorsServiceClient interface {
}

type xatuPublicContributorsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewXatuPublicContributorsServiceClient(cc grpc.ClientConnInterface) XatuPublicContributorsServiceClient {
	return &xatuPublicContributorsServiceClient{cc}
}

// XatuPublicContributorsServiceServer is the server API for XatuPublicContributorsService service.
// All implementations must embed UnimplementedXatuPublicContributorsServiceServer
// for forward compatibility.
//
// The xatu_public_contributors service definition
type XatuPublicContributorsServiceServer interface {
	mustEmbedUnimplementedXatuPublicContributorsServiceServer()
}

// UnimplementedXatuPublicContributorsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedXatuPublicContributorsServiceServer struct{}

func (UnimplementedXatuPublicContributorsServiceServer) mustEmbedUnimplementedXatuPublicContributorsServiceServer() {
}
func (UnimplementedXatuPublicContributorsServiceServer) testEmbeddedByValue() {}

// UnsafeXatuPublicContributorsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XatuPublicContributorsServiceServer will
// result in compilation errors.
type UnsafeXatuPublicContributorsServiceServer interface {
	mustEmbedUnimplementedXatuPublicContributorsServiceServer()
}

func RegisterXatuPublicContributorsServiceServer(s grpc.ServiceRegistrar, srv XatuPublicContributorsServiceServer) {
	// If the following call pancis, it indicates UnimplementedXatuPublicContributorsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&XatuPublicContributorsService_ServiceDesc, srv)
}

// XatuPublicContributorsService_ServiceDesc is the grpc.ServiceDesc for XatuPublicContributorsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XatuPublicContributorsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xatu_public_contributors.XatuPublicContributorsService",
	HandlerType: (*XatuPublicContributorsServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "pkg/server/proto/xatu_public_contributors/xatu_public_contributors.proto",
}
