// Code generated by generate_query_methods.go; DO NOT EDIT.

package xatuclickhouse

import (
	"context"
	"time"

	"github.com/ethpandaops/lab/pkg/xatuclickhouse/models"
)

// MempoolTransactionParams defines parameters for querying mempool_transaction table
type MempoolTransactionParams struct {
	UpdatedDateTime *time.Time
	StartUpdatedDateTime *time.Time
	EndUpdatedDateTime *time.Time
	EventDateTime *time.Time
	StartEventDateTime *time.Time
	EndEventDateTime *time.Time
	Hash *string
	From *string
	To *string
	Nonce *uint64
	Limit  *uint64
	Offset *uint64
}

// MempoolTransaction queries the mempool_transaction table
func (x *XatuClickhouse) MempoolTransaction(
	ctx context.Context,
	params MempoolTransactionParams,
) ([]models.MempoolTransaction, error) {
	newModel := func() Model {
		return &models.MempoolTransaction{}
	}

	results, err := x.QueryWithModel(ctx, newModel, params)
	if err != nil {
		return nil, err
	}

	typedResults := make([]models.MempoolTransaction, len(results))
	for i, result := range results {
		typedResults[i] = *result.(*models.MempoolTransaction)
	}

	return typedResults, nil
}

