// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.1
// source: pkg/server/proto/beacon_chain_timings/beacon_chain_timings.proto

package beacon_chain_timings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TimeWindowConfig represents a time window for processing
type TimeWindowConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	RangeMs       int64                  `protobuf:"varint,3,opt,name=range_ms,json=rangeMs,proto3" json:"range_ms,omitempty"` // Duration in milliseconds
	StepMs        int64                  `protobuf:"varint,4,opt,name=step_ms,json=stepMs,proto3" json:"step_ms,omitempty"`    // Duration in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeWindowConfig) Reset() {
	*x = TimeWindowConfig{}
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeWindowConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeWindowConfig) ProtoMessage() {}

func (x *TimeWindowConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeWindowConfig.ProtoReflect.Descriptor instead.
func (*TimeWindowConfig) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescGZIP(), []int{0}
}

func (x *TimeWindowConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TimeWindowConfig) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *TimeWindowConfig) GetRangeMs() int64 {
	if x != nil {
		return x.RangeMs
	}
	return 0
}

func (x *TimeWindowConfig) GetStepMs() int64 {
	if x != nil {
		return x.StepMs
	}
	return 0
}

type DataProcessorParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	WindowName    string                 `protobuf:"bytes,2,opt,name=window_name,json=windowName,proto3" json:"window_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataProcessorParams) Reset() {
	*x = DataProcessorParams{}
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataProcessorParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataProcessorParams) ProtoMessage() {}

func (x *DataProcessorParams) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataProcessorParams.ProtoReflect.Descriptor instead.
func (*DataProcessorParams) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescGZIP(), []int{1}
}

func (x *DataProcessorParams) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DataProcessorParams) GetWindowName() string {
	if x != nil {
		return x.WindowName
	}
	return ""
}

type BlockTimingsProcessorParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	WindowName    string                 `protobuf:"bytes,2,opt,name=window_name,json=windowName,proto3" json:"window_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockTimingsProcessorParams) Reset() {
	*x = BlockTimingsProcessorParams{}
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockTimingsProcessorParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockTimingsProcessorParams) ProtoMessage() {}

func (x *BlockTimingsProcessorParams) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockTimingsProcessorParams.ProtoReflect.Descriptor instead.
func (*BlockTimingsProcessorParams) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescGZIP(), []int{2}
}

func (x *BlockTimingsProcessorParams) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *BlockTimingsProcessorParams) GetWindowName() string {
	if x != nil {
		return x.WindowName
	}
	return ""
}

type SizeCDFProcessorParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	WindowName    string                 `protobuf:"bytes,2,opt,name=window_name,json=windowName,proto3" json:"window_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizeCDFProcessorParams) Reset() {
	*x = SizeCDFProcessorParams{}
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeCDFProcessorParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeCDFProcessorParams) ProtoMessage() {}

func (x *SizeCDFProcessorParams) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeCDFProcessorParams.ProtoReflect.Descriptor instead.
func (*SizeCDFProcessorParams) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescGZIP(), []int{3}
}

func (x *SizeCDFProcessorParams) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *SizeCDFProcessorParams) GetWindowName() string {
	if x != nil {
		return x.WindowName
	}
	return ""
}

// ProcessorState tracks the processing state for a specific processor
type ProcessorState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	LastProcessed *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_processed,json=lastProcessed,proto3" json:"last_processed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessorState) Reset() {
	*x = ProcessorState{}
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessorState) ProtoMessage() {}

func (x *ProcessorState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessorState.ProtoReflect.Descriptor instead.
func (*ProcessorState) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessorState) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ProcessorState) GetLastProcessed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastProcessed
	}
	return nil
}

// TimingData represents block timing statistics in time windows
type TimingData struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Network       string                                   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Timestamp     *timestamppb.Timestamp                   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Timestamps    []int64                                  `protobuf:"varint,3,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"`
	Mins          []float64                                `protobuf:"fixed64,4,rep,packed,name=mins,proto3" json:"mins,omitempty"`
	Maxs          []float64                                `protobuf:"fixed64,5,rep,packed,name=maxs,proto3" json:"maxs,omitempty"`
	Avgs          []float64                                `protobuf:"fixed64,6,rep,packed,name=avgs,proto3" json:"avgs,omitempty"`
	P05S          []float64                                `protobuf:"fixed64,7,rep,packed,name=p05s,proto3" json:"p05s,omitempty"`
	P50S          []float64                                `protobuf:"fixed64,8,rep,packed,name=p50s,proto3" json:"p50s,omitempty"`
	P95S          []float64                                `protobuf:"fixed64,9,rep,packed,name=p95s,proto3" json:"p95s,omitempty"`
	Blocks        []int64                                  `protobuf:"varint,10,rep,packed,name=blocks,proto3" json:"blocks,omitempty"`
	Validators    map[string]*TimingData_ValidatorCategory `protobuf:"bytes,11,rep,name=validators,proto3" json:"validators,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // validator -> timing categories
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimingData) Reset() {
	*x = TimingData{}
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimingData) ProtoMessage() {}

func (x *TimingData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimingData.ProtoReflect.Descriptor instead.
func (*TimingData) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescGZIP(), []int{5}
}

func (x *TimingData) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *TimingData) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TimingData) GetTimestamps() []int64 {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *TimingData) GetMins() []float64 {
	if x != nil {
		return x.Mins
	}
	return nil
}

func (x *TimingData) GetMaxs() []float64 {
	if x != nil {
		return x.Maxs
	}
	return nil
}

func (x *TimingData) GetAvgs() []float64 {
	if x != nil {
		return x.Avgs
	}
	return nil
}

func (x *TimingData) GetP05S() []float64 {
	if x != nil {
		return x.P05S
	}
	return nil
}

func (x *TimingData) GetP50S() []float64 {
	if x != nil {
		return x.P50S
	}
	return nil
}

func (x *TimingData) GetP95S() []float64 {
	if x != nil {
		return x.P95S
	}
	return nil
}

func (x *TimingData) GetBlocks() []int64 {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *TimingData) GetValidators() map[string]*TimingData_ValidatorCategory {
	if x != nil {
		return x.Validators
	}
	return nil
}

// SizeCDFData represents size CDF (Cumulative Distribution Function) data
type SizeCDFData struct {
	state          protoimpl.MessageState             `protogen:"open.v1"`
	Network        string                             `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Timestamp      *timestamppb.Timestamp             `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SizesKb        []int64                            `protobuf:"varint,3,rep,packed,name=sizes_kb,json=sizesKb,proto3" json:"sizes_kb,omitempty"`
	Mev            map[string]float64                 `protobuf:"bytes,4,rep,name=mev,proto3" json:"mev,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	NonMev         map[string]float64                 `protobuf:"bytes,5,rep,name=non_mev,json=nonMev,proto3" json:"non_mev,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	SoloMev        map[string]float64                 `protobuf:"bytes,6,rep,name=solo_mev,json=soloMev,proto3" json:"solo_mev,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	SoloNonMev     map[string]float64                 `protobuf:"bytes,7,rep,name=solo_non_mev,json=soloNonMev,proto3" json:"solo_non_mev,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	All            map[string]float64                 `protobuf:"bytes,8,rep,name=all,proto3" json:"all,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	ArrivalTimesMs map[string]*SizeCDFData_DoubleList `protobuf:"bytes,9,rep,name=arrival_times_ms,json=arrivalTimesMs,proto3" json:"arrival_times_ms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SizeCDFData) Reset() {
	*x = SizeCDFData{}
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeCDFData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeCDFData) ProtoMessage() {}

func (x *SizeCDFData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeCDFData.ProtoReflect.Descriptor instead.
func (*SizeCDFData) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescGZIP(), []int{6}
}

func (x *SizeCDFData) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *SizeCDFData) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SizeCDFData) GetSizesKb() []int64 {
	if x != nil {
		return x.SizesKb
	}
	return nil
}

func (x *SizeCDFData) GetMev() map[string]float64 {
	if x != nil {
		return x.Mev
	}
	return nil
}

func (x *SizeCDFData) GetNonMev() map[string]float64 {
	if x != nil {
		return x.NonMev
	}
	return nil
}

func (x *SizeCDFData) GetSoloMev() map[string]float64 {
	if x != nil {
		return x.SoloMev
	}
	return nil
}

func (x *SizeCDFData) GetSoloNonMev() map[string]float64 {
	if x != nil {
		return x.SoloNonMev
	}
	return nil
}

func (x *SizeCDFData) GetAll() map[string]float64 {
	if x != nil {
		return x.All
	}
	return nil
}

func (x *SizeCDFData) GetArrivalTimesMs() map[string]*SizeCDFData_DoubleList {
	if x != nil {
		return x.ArrivalTimesMs
	}
	return nil
}

// Request and response messages for the service methods
type GetTimingDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	WindowName    string                 `protobuf:"bytes,2,opt,name=window_name,json=windowName,proto3" json:"window_name,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimingDataRequest) Reset() {
	*x = GetTimingDataRequest{}
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimingDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimingDataRequest) ProtoMessage() {}

func (x *GetTimingDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimingDataRequest.ProtoReflect.Descriptor instead.
func (*GetTimingDataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescGZIP(), []int{7}
}

func (x *GetTimingDataRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *GetTimingDataRequest) GetWindowName() string {
	if x != nil {
		return x.WindowName
	}
	return ""
}

func (x *GetTimingDataRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetTimingDataRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type GetTimingDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*TimingData          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimingDataResponse) Reset() {
	*x = GetTimingDataResponse{}
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimingDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimingDataResponse) ProtoMessage() {}

func (x *GetTimingDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimingDataResponse.ProtoReflect.Descriptor instead.
func (*GetTimingDataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescGZIP(), []int{8}
}

func (x *GetTimingDataResponse) GetData() []*TimingData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetSizeCDFDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSizeCDFDataRequest) Reset() {
	*x = GetSizeCDFDataRequest{}
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSizeCDFDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSizeCDFDataRequest) ProtoMessage() {}

func (x *GetSizeCDFDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSizeCDFDataRequest.ProtoReflect.Descriptor instead.
func (*GetSizeCDFDataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescGZIP(), []int{9}
}

func (x *GetSizeCDFDataRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *GetSizeCDFDataRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetSizeCDFDataRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type GetSizeCDFDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*SizeCDFData         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSizeCDFDataResponse) Reset() {
	*x = GetSizeCDFDataResponse{}
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSizeCDFDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSizeCDFDataResponse) ProtoMessage() {}

func (x *GetSizeCDFDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSizeCDFDataResponse.ProtoReflect.Descriptor instead.
func (*GetSizeCDFDataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescGZIP(), []int{10}
}

func (x *GetSizeCDFDataResponse) GetData() []*SizeCDFData {
	if x != nil {
		return x.Data
	}
	return nil
}

// State tracks processing state for all data types
type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockTimings  *DataTypeState         `protobuf:"bytes,1,opt,name=block_timings,json=blockTimings,proto3" json:"block_timings,omitempty"`
	Cdf           *DataTypeState         `protobuf:"bytes,2,opt,name=cdf,proto3" json:"cdf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescGZIP(), []int{11}
}

func (x *State) GetBlockTimings() *DataTypeState {
	if x != nil {
		return x.BlockTimings
	}
	return nil
}

func (x *State) GetCdf() *DataTypeState {
	if x != nil {
		return x.Cdf
	}
	return nil
}

// DataTypeState tracks processing state for a specific data type
type DataTypeState struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	LastProcessed map[string]*timestamppb.Timestamp `protobuf:"bytes,1,rep,name=last_processed,json=lastProcessed,proto3" json:"last_processed,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataTypeState) Reset() {
	*x = DataTypeState{}
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataTypeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTypeState) ProtoMessage() {}

func (x *DataTypeState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTypeState.ProtoReflect.Descriptor instead.
func (*DataTypeState) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescGZIP(), []int{12}
}

func (x *DataTypeState) GetLastProcessed() map[string]*timestamppb.Timestamp {
	if x != nil {
		return x.LastProcessed
	}
	return nil
}

// Validator timing data
type TimingData_ValidatorCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    map[string]int32       `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // timing category -> count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimingData_ValidatorCategory) Reset() {
	*x = TimingData_ValidatorCategory{}
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimingData_ValidatorCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimingData_ValidatorCategory) ProtoMessage() {}

func (x *TimingData_ValidatorCategory) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimingData_ValidatorCategory.ProtoReflect.Descriptor instead.
func (*TimingData_ValidatorCategory) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescGZIP(), []int{5, 0}
}

func (x *TimingData_ValidatorCategory) GetCategories() map[string]int32 {
	if x != nil {
		return x.Categories
	}
	return nil
}

type SizeCDFData_DoubleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizeCDFData_DoubleList) Reset() {
	*x = SizeCDFData_DoubleList{}
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeCDFData_DoubleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeCDFData_DoubleList) ProtoMessage() {}

func (x *SizeCDFData_DoubleList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeCDFData_DoubleList.ProtoReflect.Descriptor instead.
func (*SizeCDFData_DoubleList) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescGZIP(), []int{6, 5}
}

func (x *SizeCDFData_DoubleList) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto protoreflect.FileDescriptor

const file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDesc = "" +
	"\n" +
	"@pkg/server/proto/beacon_chain_timings/beacon_chain_timings.proto\x12\x14beacon_chain_timings\x1a\x1fgoogle/protobuf/timestamp.proto\"n\n" +
	"\x10TimeWindowConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x19\n" +
	"\brange_ms\x18\x03 \x01(\x03R\arangeMs\x12\x17\n" +
	"\astep_ms\x18\x04 \x01(\x03R\x06stepMs\"P\n" +
	"\x13DataProcessorParams\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x1f\n" +
	"\vwindow_name\x18\x02 \x01(\tR\n" +
	"windowName\"X\n" +
	"\x1bBlockTimingsProcessorParams\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x1f\n" +
	"\vwindow_name\x18\x02 \x01(\tR\n" +
	"windowName\"S\n" +
	"\x16SizeCDFProcessorParams\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x1f\n" +
	"\vwindow_name\x18\x02 \x01(\tR\n" +
	"windowName\"m\n" +
	"\x0eProcessorState\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12A\n" +
	"\x0elast_processed\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rlastProcessed\"\x8e\x05\n" +
	"\n" +
	"TimingData\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x03 \x03(\x03R\n" +
	"timestamps\x12\x12\n" +
	"\x04mins\x18\x04 \x03(\x01R\x04mins\x12\x12\n" +
	"\x04maxs\x18\x05 \x03(\x01R\x04maxs\x12\x12\n" +
	"\x04avgs\x18\x06 \x03(\x01R\x04avgs\x12\x12\n" +
	"\x04p05s\x18\a \x03(\x01R\x04p05s\x12\x12\n" +
	"\x04p50s\x18\b \x03(\x01R\x04p50s\x12\x12\n" +
	"\x04p95s\x18\t \x03(\x01R\x04p95s\x12\x16\n" +
	"\x06blocks\x18\n" +
	" \x03(\x03R\x06blocks\x12P\n" +
	"\n" +
	"validators\x18\v \x03(\v20.beacon_chain_timings.TimingData.ValidatorsEntryR\n" +
	"validators\x1a\xb6\x01\n" +
	"\x11ValidatorCategory\x12b\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2B.beacon_chain_timings.TimingData.ValidatorCategory.CategoriesEntryR\n" +
	"categories\x1a=\n" +
	"\x0fCategoriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aq\n" +
	"\x0fValidatorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12H\n" +
	"\x05value\x18\x02 \x01(\v22.beacon_chain_timings.TimingData.ValidatorCategoryR\x05value:\x028\x01\"\xfe\a\n" +
	"\vSizeCDFData\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\bsizes_kb\x18\x03 \x03(\x03R\asizesKb\x12<\n" +
	"\x03mev\x18\x04 \x03(\v2*.beacon_chain_timings.SizeCDFData.MevEntryR\x03mev\x12F\n" +
	"\anon_mev\x18\x05 \x03(\v2-.beacon_chain_timings.SizeCDFData.NonMevEntryR\x06nonMev\x12I\n" +
	"\bsolo_mev\x18\x06 \x03(\v2..beacon_chain_timings.SizeCDFData.SoloMevEntryR\asoloMev\x12S\n" +
	"\fsolo_non_mev\x18\a \x03(\v21.beacon_chain_timings.SizeCDFData.SoloNonMevEntryR\n" +
	"soloNonMev\x12<\n" +
	"\x03all\x18\b \x03(\v2*.beacon_chain_timings.SizeCDFData.AllEntryR\x03all\x12_\n" +
	"\x10arrival_times_ms\x18\t \x03(\v25.beacon_chain_timings.SizeCDFData.ArrivalTimesMsEntryR\x0earrivalTimesMs\x1a6\n" +
	"\bMevEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a9\n" +
	"\vNonMevEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a:\n" +
	"\fSoloMevEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a=\n" +
	"\x0fSoloNonMevEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a6\n" +
	"\bAllEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a$\n" +
	"\n" +
	"DoubleList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\x1ao\n" +
	"\x13ArrivalTimesMsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12B\n" +
	"\x05value\x18\x02 \x01(\v2,.beacon_chain_timings.SizeCDFData.DoubleListR\x05value:\x028\x01\"\xc3\x01\n" +
	"\x14GetTimingDataRequest\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x1f\n" +
	"\vwindow_name\x18\x02 \x01(\tR\n" +
	"windowName\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"M\n" +
	"\x15GetTimingDataResponse\x124\n" +
	"\x04data\x18\x01 \x03(\v2 .beacon_chain_timings.TimingDataR\x04data\"\xa3\x01\n" +
	"\x15GetSizeCDFDataRequest\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"O\n" +
	"\x16GetSizeCDFDataResponse\x125\n" +
	"\x04data\x18\x01 \x03(\v2!.beacon_chain_timings.SizeCDFDataR\x04data\"\x88\x01\n" +
	"\x05State\x12H\n" +
	"\rblock_timings\x18\x01 \x01(\v2#.beacon_chain_timings.DataTypeStateR\fblockTimings\x125\n" +
	"\x03cdf\x18\x02 \x01(\v2#.beacon_chain_timings.DataTypeStateR\x03cdf\"\xcc\x01\n" +
	"\rDataTypeState\x12]\n" +
	"\x0elast_processed\x18\x01 \x03(\v26.beacon_chain_timings.DataTypeState.LastProcessedEntryR\rlastProcessed\x1a\\\n" +
	"\x12LastProcessedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05value:\x028\x012\xf2\x01\n" +
	"\x19BeaconChainTimingsService\x12h\n" +
	"\rGetTimingData\x12*.beacon_chain_timings.GetTimingDataRequest\x1a+.beacon_chain_timings.GetTimingDataResponse\x12k\n" +
	"\x0eGetSizeCDFData\x12+.beacon_chain_timings.GetSizeCDFDataRequest\x1a,.beacon_chain_timings.GetSizeCDFDataResponseB;Z9github.com/ethpandaops/lab/pkg/proto/beacon_chain_timingsb\x06proto3"

var (
	file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescOnce sync.Once
	file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescData []byte
)

func file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescGZIP() []byte {
	file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescOnce.Do(func() {
		file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDesc), len(file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDesc)))
	})
	return file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDescData
}

var file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_goTypes = []any{
	(*TimeWindowConfig)(nil),             // 0: beacon_chain_timings.TimeWindowConfig
	(*DataProcessorParams)(nil),          // 1: beacon_chain_timings.DataProcessorParams
	(*BlockTimingsProcessorParams)(nil),  // 2: beacon_chain_timings.BlockTimingsProcessorParams
	(*SizeCDFProcessorParams)(nil),       // 3: beacon_chain_timings.SizeCDFProcessorParams
	(*ProcessorState)(nil),               // 4: beacon_chain_timings.ProcessorState
	(*TimingData)(nil),                   // 5: beacon_chain_timings.TimingData
	(*SizeCDFData)(nil),                  // 6: beacon_chain_timings.SizeCDFData
	(*GetTimingDataRequest)(nil),         // 7: beacon_chain_timings.GetTimingDataRequest
	(*GetTimingDataResponse)(nil),        // 8: beacon_chain_timings.GetTimingDataResponse
	(*GetSizeCDFDataRequest)(nil),        // 9: beacon_chain_timings.GetSizeCDFDataRequest
	(*GetSizeCDFDataResponse)(nil),       // 10: beacon_chain_timings.GetSizeCDFDataResponse
	(*State)(nil),                        // 11: beacon_chain_timings.State
	(*DataTypeState)(nil),                // 12: beacon_chain_timings.DataTypeState
	(*TimingData_ValidatorCategory)(nil), // 13: beacon_chain_timings.TimingData.ValidatorCategory
	nil,                                  // 14: beacon_chain_timings.TimingData.ValidatorsEntry
	nil,                                  // 15: beacon_chain_timings.TimingData.ValidatorCategory.CategoriesEntry
	nil,                                  // 16: beacon_chain_timings.SizeCDFData.MevEntry
	nil,                                  // 17: beacon_chain_timings.SizeCDFData.NonMevEntry
	nil,                                  // 18: beacon_chain_timings.SizeCDFData.SoloMevEntry
	nil,                                  // 19: beacon_chain_timings.SizeCDFData.SoloNonMevEntry
	nil,                                  // 20: beacon_chain_timings.SizeCDFData.AllEntry
	(*SizeCDFData_DoubleList)(nil),       // 21: beacon_chain_timings.SizeCDFData.DoubleList
	nil,                                  // 22: beacon_chain_timings.SizeCDFData.ArrivalTimesMsEntry
	nil,                                  // 23: beacon_chain_timings.DataTypeState.LastProcessedEntry
	(*timestamppb.Timestamp)(nil),        // 24: google.protobuf.Timestamp
}
var file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_depIdxs = []int32{
	24, // 0: beacon_chain_timings.ProcessorState.last_processed:type_name -> google.protobuf.Timestamp
	24, // 1: beacon_chain_timings.TimingData.timestamp:type_name -> google.protobuf.Timestamp
	14, // 2: beacon_chain_timings.TimingData.validators:type_name -> beacon_chain_timings.TimingData.ValidatorsEntry
	24, // 3: beacon_chain_timings.SizeCDFData.timestamp:type_name -> google.protobuf.Timestamp
	16, // 4: beacon_chain_timings.SizeCDFData.mev:type_name -> beacon_chain_timings.SizeCDFData.MevEntry
	17, // 5: beacon_chain_timings.SizeCDFData.non_mev:type_name -> beacon_chain_timings.SizeCDFData.NonMevEntry
	18, // 6: beacon_chain_timings.SizeCDFData.solo_mev:type_name -> beacon_chain_timings.SizeCDFData.SoloMevEntry
	19, // 7: beacon_chain_timings.SizeCDFData.solo_non_mev:type_name -> beacon_chain_timings.SizeCDFData.SoloNonMevEntry
	20, // 8: beacon_chain_timings.SizeCDFData.all:type_name -> beacon_chain_timings.SizeCDFData.AllEntry
	22, // 9: beacon_chain_timings.SizeCDFData.arrival_times_ms:type_name -> beacon_chain_timings.SizeCDFData.ArrivalTimesMsEntry
	24, // 10: beacon_chain_timings.GetTimingDataRequest.start_time:type_name -> google.protobuf.Timestamp
	24, // 11: beacon_chain_timings.GetTimingDataRequest.end_time:type_name -> google.protobuf.Timestamp
	5,  // 12: beacon_chain_timings.GetTimingDataResponse.data:type_name -> beacon_chain_timings.TimingData
	24, // 13: beacon_chain_timings.GetSizeCDFDataRequest.start_time:type_name -> google.protobuf.Timestamp
	24, // 14: beacon_chain_timings.GetSizeCDFDataRequest.end_time:type_name -> google.protobuf.Timestamp
	6,  // 15: beacon_chain_timings.GetSizeCDFDataResponse.data:type_name -> beacon_chain_timings.SizeCDFData
	12, // 16: beacon_chain_timings.State.block_timings:type_name -> beacon_chain_timings.DataTypeState
	12, // 17: beacon_chain_timings.State.cdf:type_name -> beacon_chain_timings.DataTypeState
	23, // 18: beacon_chain_timings.DataTypeState.last_processed:type_name -> beacon_chain_timings.DataTypeState.LastProcessedEntry
	15, // 19: beacon_chain_timings.TimingData.ValidatorCategory.categories:type_name -> beacon_chain_timings.TimingData.ValidatorCategory.CategoriesEntry
	13, // 20: beacon_chain_timings.TimingData.ValidatorsEntry.value:type_name -> beacon_chain_timings.TimingData.ValidatorCategory
	21, // 21: beacon_chain_timings.SizeCDFData.ArrivalTimesMsEntry.value:type_name -> beacon_chain_timings.SizeCDFData.DoubleList
	24, // 22: beacon_chain_timings.DataTypeState.LastProcessedEntry.value:type_name -> google.protobuf.Timestamp
	7,  // 23: beacon_chain_timings.BeaconChainTimingsService.GetTimingData:input_type -> beacon_chain_timings.GetTimingDataRequest
	9,  // 24: beacon_chain_timings.BeaconChainTimingsService.GetSizeCDFData:input_type -> beacon_chain_timings.GetSizeCDFDataRequest
	8,  // 25: beacon_chain_timings.BeaconChainTimingsService.GetTimingData:output_type -> beacon_chain_timings.GetTimingDataResponse
	10, // 26: beacon_chain_timings.BeaconChainTimingsService.GetSizeCDFData:output_type -> beacon_chain_timings.GetSizeCDFDataResponse
	25, // [25:27] is the sub-list for method output_type
	23, // [23:25] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_init() }
func file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_init() {
	if File_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDesc), len(file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_goTypes,
		DependencyIndexes: file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_depIdxs,
		MessageInfos:      file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_msgTypes,
	}.Build()
	File_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto = out.File
	file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_goTypes = nil
	file_pkg_server_proto_beacon_chain_timings_beacon_chain_timings_proto_depIdxs = nil
}
