// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: backend/pkg/server/proto/xatu_cbt/xatu_cbt.proto

package xatu_cbt

import (
	context "context"
	clickhouse "github.com/ethpandaops/xatu-cbt/pkg/proto/clickhouse"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	XatuCBT_ListIntXatuNodes24H_FullMethodName = "/xatu_cbt.XatuCBT/ListIntXatuNodes24H"
)

// XatuCBTClient is the client API for XatuCBT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// XatuCBT service provides access to CBT data from multiple ClickHouse instances.
// Each RPC corresponds to a specific CBT table/view and uses upstream request/response types.
type XatuCBTClient interface {
	// ListIntXatuNodes24H queries the intermediate 24-hour aggregated nodes table.
	// This table contains node metadata aggregated over rolling 24-hour periods.
	ListIntXatuNodes24H(ctx context.Context, in *clickhouse.ListIntXatuNodes24HRequest, opts ...grpc.CallOption) (*clickhouse.ListIntXatuNodes24HResponse, error)
}

type xatuCBTClient struct {
	cc grpc.ClientConnInterface
}

func NewXatuCBTClient(cc grpc.ClientConnInterface) XatuCBTClient {
	return &xatuCBTClient{cc}
}

func (c *xatuCBTClient) ListIntXatuNodes24H(ctx context.Context, in *clickhouse.ListIntXatuNodes24HRequest, opts ...grpc.CallOption) (*clickhouse.ListIntXatuNodes24HResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(clickhouse.ListIntXatuNodes24HResponse)
	err := c.cc.Invoke(ctx, XatuCBT_ListIntXatuNodes24H_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XatuCBTServer is the server API for XatuCBT service.
// All implementations must embed UnimplementedXatuCBTServer
// for forward compatibility
//
// XatuCBT service provides access to CBT data from multiple ClickHouse instances.
// Each RPC corresponds to a specific CBT table/view and uses upstream request/response types.
type XatuCBTServer interface {
	// ListIntXatuNodes24H queries the intermediate 24-hour aggregated nodes table.
	// This table contains node metadata aggregated over rolling 24-hour periods.
	ListIntXatuNodes24H(context.Context, *clickhouse.ListIntXatuNodes24HRequest) (*clickhouse.ListIntXatuNodes24HResponse, error)
	mustEmbedUnimplementedXatuCBTServer()
}

// UnimplementedXatuCBTServer must be embedded to have forward compatible implementations.
type UnimplementedXatuCBTServer struct {
}

func (UnimplementedXatuCBTServer) ListIntXatuNodes24H(context.Context, *clickhouse.ListIntXatuNodes24HRequest) (*clickhouse.ListIntXatuNodes24HResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIntXatuNodes24H not implemented")
}
func (UnimplementedXatuCBTServer) mustEmbedUnimplementedXatuCBTServer() {}

// UnsafeXatuCBTServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XatuCBTServer will
// result in compilation errors.
type UnsafeXatuCBTServer interface {
	mustEmbedUnimplementedXatuCBTServer()
}

func RegisterXatuCBTServer(s grpc.ServiceRegistrar, srv XatuCBTServer) {
	s.RegisterService(&XatuCBT_ServiceDesc, srv)
}

func _XatuCBT_ListIntXatuNodes24H_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(clickhouse.ListIntXatuNodes24HRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XatuCBTServer).ListIntXatuNodes24H(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XatuCBT_ListIntXatuNodes24H_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XatuCBTServer).ListIntXatuNodes24H(ctx, req.(*clickhouse.ListIntXatuNodes24HRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XatuCBT_ServiceDesc is the grpc.ServiceDesc for XatuCBT service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XatuCBT_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xatu_cbt.XatuCBT",
	HandlerType: (*XatuCBTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListIntXatuNodes24H",
			Handler:    _XatuCBT_ListIntXatuNodes24H_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/pkg/server/proto/xatu_cbt/xatu_cbt.proto",
}
