/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XatuRouteImport } from './routes/xatu'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as EthereumRouteImport } from './routes/ethereum'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperimentsIndexRouteImport } from './routes/experiments/index'
import { Route as XatuLocallyBuiltBlocksRouteImport } from './routes/xatu/locally-built-blocks'
import { Route as XatuGeographicalChecklistRouteImport } from './routes/xatu/geographical-checklist'
import { Route as XatuForkReadinessRouteImport } from './routes/xatu/fork-readiness'
import { Route as XatuContributorsRouteImport } from './routes/xatu/contributors'
import { Route as EthereumSlotViewRouteImport } from './routes/ethereum/slot-view'
import { Route as XatuContributorsIndexRouteImport } from './routes/xatu/contributors/index'
import { Route as XatuContributorsIdRouteImport } from './routes/xatu/contributors/$id'

const XatuRoute = XatuRouteImport.update({
  id: '/xatu',
  path: '/xatu',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const EthereumRoute = EthereumRouteImport.update({
  id: '/ethereum',
  path: '/ethereum',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsIndexRoute = ExperimentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExperimentsRoute,
} as any)
const XatuLocallyBuiltBlocksRoute = XatuLocallyBuiltBlocksRouteImport.update({
  id: '/locally-built-blocks',
  path: '/locally-built-blocks',
  getParentRoute: () => XatuRoute,
} as any)
const XatuGeographicalChecklistRoute =
  XatuGeographicalChecklistRouteImport.update({
    id: '/geographical-checklist',
    path: '/geographical-checklist',
    getParentRoute: () => XatuRoute,
  } as any)
const XatuForkReadinessRoute = XatuForkReadinessRouteImport.update({
  id: '/fork-readiness',
  path: '/fork-readiness',
  getParentRoute: () => XatuRoute,
} as any)
const XatuContributorsRoute = XatuContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => XatuRoute,
} as any)
const EthereumSlotViewRoute = EthereumSlotViewRouteImport.update({
  id: '/slot-view',
  path: '/slot-view',
  getParentRoute: () => EthereumRoute,
} as any)
const XatuContributorsIndexRoute = XatuContributorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => XatuContributorsRoute,
} as any)
const XatuContributorsIdRoute = XatuContributorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => XatuContributorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ethereum': typeof EthereumRouteWithChildren
  '/experiments': typeof ExperimentsRouteWithChildren
  '/xatu': typeof XatuRouteWithChildren
  '/ethereum/slot-view': typeof EthereumSlotViewRoute
  '/xatu/contributors': typeof XatuContributorsRouteWithChildren
  '/xatu/fork-readiness': typeof XatuForkReadinessRoute
  '/xatu/geographical-checklist': typeof XatuGeographicalChecklistRoute
  '/xatu/locally-built-blocks': typeof XatuLocallyBuiltBlocksRoute
  '/experiments/': typeof ExperimentsIndexRoute
  '/xatu/contributors/$id': typeof XatuContributorsIdRoute
  '/xatu/contributors/': typeof XatuContributorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ethereum': typeof EthereumRouteWithChildren
  '/xatu': typeof XatuRouteWithChildren
  '/ethereum/slot-view': typeof EthereumSlotViewRoute
  '/xatu/fork-readiness': typeof XatuForkReadinessRoute
  '/xatu/geographical-checklist': typeof XatuGeographicalChecklistRoute
  '/xatu/locally-built-blocks': typeof XatuLocallyBuiltBlocksRoute
  '/experiments': typeof ExperimentsIndexRoute
  '/xatu/contributors/$id': typeof XatuContributorsIdRoute
  '/xatu/contributors': typeof XatuContributorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ethereum': typeof EthereumRouteWithChildren
  '/experiments': typeof ExperimentsRouteWithChildren
  '/xatu': typeof XatuRouteWithChildren
  '/ethereum/slot-view': typeof EthereumSlotViewRoute
  '/xatu/contributors': typeof XatuContributorsRouteWithChildren
  '/xatu/fork-readiness': typeof XatuForkReadinessRoute
  '/xatu/geographical-checklist': typeof XatuGeographicalChecklistRoute
  '/xatu/locally-built-blocks': typeof XatuLocallyBuiltBlocksRoute
  '/experiments/': typeof ExperimentsIndexRoute
  '/xatu/contributors/$id': typeof XatuContributorsIdRoute
  '/xatu/contributors/': typeof XatuContributorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ethereum'
    | '/experiments'
    | '/xatu'
    | '/ethereum/slot-view'
    | '/xatu/contributors'
    | '/xatu/fork-readiness'
    | '/xatu/geographical-checklist'
    | '/xatu/locally-built-blocks'
    | '/experiments/'
    | '/xatu/contributors/$id'
    | '/xatu/contributors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ethereum'
    | '/xatu'
    | '/ethereum/slot-view'
    | '/xatu/fork-readiness'
    | '/xatu/geographical-checklist'
    | '/xatu/locally-built-blocks'
    | '/experiments'
    | '/xatu/contributors/$id'
    | '/xatu/contributors'
  id:
    | '__root__'
    | '/'
    | '/ethereum'
    | '/experiments'
    | '/xatu'
    | '/ethereum/slot-view'
    | '/xatu/contributors'
    | '/xatu/fork-readiness'
    | '/xatu/geographical-checklist'
    | '/xatu/locally-built-blocks'
    | '/experiments/'
    | '/xatu/contributors/$id'
    | '/xatu/contributors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EthereumRoute: typeof EthereumRouteWithChildren
  ExperimentsRoute: typeof ExperimentsRouteWithChildren
  XatuRoute: typeof XatuRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xatu': {
      id: '/xatu'
      path: '/xatu'
      fullPath: '/xatu'
      preLoaderRoute: typeof XatuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethereum': {
      id: '/ethereum'
      path: '/ethereum'
      fullPath: '/ethereum'
      preLoaderRoute: typeof EthereumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/': {
      id: '/experiments/'
      path: '/'
      fullPath: '/experiments/'
      preLoaderRoute: typeof ExperimentsIndexRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/xatu/locally-built-blocks': {
      id: '/xatu/locally-built-blocks'
      path: '/locally-built-blocks'
      fullPath: '/xatu/locally-built-blocks'
      preLoaderRoute: typeof XatuLocallyBuiltBlocksRouteImport
      parentRoute: typeof XatuRoute
    }
    '/xatu/geographical-checklist': {
      id: '/xatu/geographical-checklist'
      path: '/geographical-checklist'
      fullPath: '/xatu/geographical-checklist'
      preLoaderRoute: typeof XatuGeographicalChecklistRouteImport
      parentRoute: typeof XatuRoute
    }
    '/xatu/fork-readiness': {
      id: '/xatu/fork-readiness'
      path: '/fork-readiness'
      fullPath: '/xatu/fork-readiness'
      preLoaderRoute: typeof XatuForkReadinessRouteImport
      parentRoute: typeof XatuRoute
    }
    '/xatu/contributors': {
      id: '/xatu/contributors'
      path: '/contributors'
      fullPath: '/xatu/contributors'
      preLoaderRoute: typeof XatuContributorsRouteImport
      parentRoute: typeof XatuRoute
    }
    '/ethereum/slot-view': {
      id: '/ethereum/slot-view'
      path: '/slot-view'
      fullPath: '/ethereum/slot-view'
      preLoaderRoute: typeof EthereumSlotViewRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/xatu/contributors/': {
      id: '/xatu/contributors/'
      path: '/'
      fullPath: '/xatu/contributors/'
      preLoaderRoute: typeof XatuContributorsIndexRouteImport
      parentRoute: typeof XatuContributorsRoute
    }
    '/xatu/contributors/$id': {
      id: '/xatu/contributors/$id'
      path: '/$id'
      fullPath: '/xatu/contributors/$id'
      preLoaderRoute: typeof XatuContributorsIdRouteImport
      parentRoute: typeof XatuContributorsRoute
    }
  }
}

interface EthereumRouteChildren {
  EthereumSlotViewRoute: typeof EthereumSlotViewRoute
}

const EthereumRouteChildren: EthereumRouteChildren = {
  EthereumSlotViewRoute: EthereumSlotViewRoute,
}

const EthereumRouteWithChildren = EthereumRoute._addFileChildren(
  EthereumRouteChildren,
)

interface ExperimentsRouteChildren {
  ExperimentsIndexRoute: typeof ExperimentsIndexRoute
}

const ExperimentsRouteChildren: ExperimentsRouteChildren = {
  ExperimentsIndexRoute: ExperimentsIndexRoute,
}

const ExperimentsRouteWithChildren = ExperimentsRoute._addFileChildren(
  ExperimentsRouteChildren,
)

interface XatuContributorsRouteChildren {
  XatuContributorsIdRoute: typeof XatuContributorsIdRoute
  XatuContributorsIndexRoute: typeof XatuContributorsIndexRoute
}

const XatuContributorsRouteChildren: XatuContributorsRouteChildren = {
  XatuContributorsIdRoute: XatuContributorsIdRoute,
  XatuContributorsIndexRoute: XatuContributorsIndexRoute,
}

const XatuContributorsRouteWithChildren =
  XatuContributorsRoute._addFileChildren(XatuContributorsRouteChildren)

interface XatuRouteChildren {
  XatuContributorsRoute: typeof XatuContributorsRouteWithChildren
  XatuForkReadinessRoute: typeof XatuForkReadinessRoute
  XatuGeographicalChecklistRoute: typeof XatuGeographicalChecklistRoute
  XatuLocallyBuiltBlocksRoute: typeof XatuLocallyBuiltBlocksRoute
}

const XatuRouteChildren: XatuRouteChildren = {
  XatuContributorsRoute: XatuContributorsRouteWithChildren,
  XatuForkReadinessRoute: XatuForkReadinessRoute,
  XatuGeographicalChecklistRoute: XatuGeographicalChecklistRoute,
  XatuLocallyBuiltBlocksRoute: XatuLocallyBuiltBlocksRoute,
}

const XatuRouteWithChildren = XatuRoute._addFileChildren(XatuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EthereumRoute: EthereumRouteWithChildren,
  ExperimentsRoute: ExperimentsRouteWithChildren,
  XatuRoute: XatuRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
