/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XatuRouteImport } from './routes/xatu'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as EthereumRouteImport } from './routes/ethereum'
import { Route as IndexRouteImport } from './routes/index'
import { Route as XatuDataIndexRouteImport } from './routes/xatu-data/index'
import { Route as ExperimentsIndexRouteImport } from './routes/experiments/index'
import { Route as XatuLocallyBuiltBlocksRouteImport } from './routes/xatu/locally-built-blocks'
import { Route as XatuGeographicalChecklistRouteImport } from './routes/xatu/geographical-checklist'
import { Route as XatuForkReadinessRouteImport } from './routes/xatu/fork-readiness'
import { Route as XatuContributorsRouteImport } from './routes/xatu/contributors'
import { Route as XatuDataGeographicalChecklistRouteImport } from './routes/xatu-data/geographical-checklist'
import { Route as XatuDataForkReadinessRouteImport } from './routes/xatu-data/fork-readiness'
import { Route as ExperimentsLiveSlotsRouteImport } from './routes/experiments/live-slots'
import { Route as ExperimentsBlockProductionFlowRouteImport } from './routes/experiments/block-production-flow'
import { Route as EthereumSlotsRouteImport } from './routes/ethereum/slots'
import { Route as EthereumLiveRouteImport } from './routes/ethereum/live'
import { Route as EthereumEpochsRouteImport } from './routes/ethereum/epochs'
import { Route as EthereumEntitiesRouteImport } from './routes/ethereum/entities'
import { Route as EthereumDataAvailabilityRouteImport } from './routes/ethereum/data-availability'
import { Route as BeaconLocallyBuiltBlocksRouteImport } from './routes/beacon/locally-built-blocks'
import { Route as XatuContributorsIndexRouteImport } from './routes/xatu/contributors/index'
import { Route as EthereumSlotsIndexRouteImport } from './routes/ethereum/slots/index'
import { Route as EthereumEpochsIndexRouteImport } from './routes/ethereum/epochs/index'
import { Route as EthereumEntitiesIndexRouteImport } from './routes/ethereum/entities/index'
import { Route as XatuContributorsIdRouteImport } from './routes/xatu/contributors/$id'
import { Route as EthereumSlotsSlotRouteImport } from './routes/ethereum/slots/$slot'
import { Route as EthereumEpochsEpochRouteImport } from './routes/ethereum/epochs/$epoch'
import { Route as EthereumEntitiesEntityRouteImport } from './routes/ethereum/entities/$entity'
import { Route as EthereumDataAvailabilityCustodyRouteImport } from './routes/ethereum/data-availability/custody'
import { Route as EthereumDataAvailabilityCustodyIndexRouteImport } from './routes/ethereum/data-availability/custody/index'

const XatuRoute = XatuRouteImport.update({
  id: '/xatu',
  path: '/xatu',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const EthereumRoute = EthereumRouteImport.update({
  id: '/ethereum',
  path: '/ethereum',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const XatuDataIndexRoute = XatuDataIndexRouteImport.update({
  id: '/xatu-data/',
  path: '/xatu-data/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsIndexRoute = ExperimentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExperimentsRoute,
} as any)
const XatuLocallyBuiltBlocksRoute = XatuLocallyBuiltBlocksRouteImport.update({
  id: '/locally-built-blocks',
  path: '/locally-built-blocks',
  getParentRoute: () => XatuRoute,
} as any)
const XatuGeographicalChecklistRoute =
  XatuGeographicalChecklistRouteImport.update({
    id: '/geographical-checklist',
    path: '/geographical-checklist',
    getParentRoute: () => XatuRoute,
  } as any)
const XatuForkReadinessRoute = XatuForkReadinessRouteImport.update({
  id: '/fork-readiness',
  path: '/fork-readiness',
  getParentRoute: () => XatuRoute,
} as any)
const XatuContributorsRoute = XatuContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => XatuRoute,
} as any)
const XatuDataGeographicalChecklistRoute =
  XatuDataGeographicalChecklistRouteImport.update({
    id: '/xatu-data/geographical-checklist',
    path: '/xatu-data/geographical-checklist',
    getParentRoute: () => rootRouteImport,
  } as any)
const XatuDataForkReadinessRoute = XatuDataForkReadinessRouteImport.update({
  id: '/xatu-data/fork-readiness',
  path: '/xatu-data/fork-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsLiveSlotsRoute = ExperimentsLiveSlotsRouteImport.update({
  id: '/live-slots',
  path: '/live-slots',
  getParentRoute: () => ExperimentsRoute,
} as any)
const ExperimentsBlockProductionFlowRoute =
  ExperimentsBlockProductionFlowRouteImport.update({
    id: '/block-production-flow',
    path: '/block-production-flow',
    getParentRoute: () => ExperimentsRoute,
  } as any)
const EthereumSlotsRoute = EthereumSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => EthereumRoute,
} as any)
const EthereumLiveRoute = EthereumLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => EthereumRoute,
} as any)
const EthereumEpochsRoute = EthereumEpochsRouteImport.update({
  id: '/epochs',
  path: '/epochs',
  getParentRoute: () => EthereumRoute,
} as any)
const EthereumEntitiesRoute = EthereumEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => EthereumRoute,
} as any)
const EthereumDataAvailabilityRoute =
  EthereumDataAvailabilityRouteImport.update({
    id: '/data-availability',
    path: '/data-availability',
    getParentRoute: () => EthereumRoute,
  } as any)
const BeaconLocallyBuiltBlocksRoute =
  BeaconLocallyBuiltBlocksRouteImport.update({
    id: '/beacon/locally-built-blocks',
    path: '/beacon/locally-built-blocks',
    getParentRoute: () => rootRouteImport,
  } as any)
const XatuContributorsIndexRoute = XatuContributorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => XatuContributorsRoute,
} as any)
const EthereumSlotsIndexRoute = EthereumSlotsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EthereumSlotsRoute,
} as any)
const EthereumEpochsIndexRoute = EthereumEpochsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EthereumEpochsRoute,
} as any)
const EthereumEntitiesIndexRoute = EthereumEntitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EthereumEntitiesRoute,
} as any)
const XatuContributorsIdRoute = XatuContributorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => XatuContributorsRoute,
} as any)
const EthereumSlotsSlotRoute = EthereumSlotsSlotRouteImport.update({
  id: '/$slot',
  path: '/$slot',
  getParentRoute: () => EthereumSlotsRoute,
} as any)
const EthereumEpochsEpochRoute = EthereumEpochsEpochRouteImport.update({
  id: '/$epoch',
  path: '/$epoch',
  getParentRoute: () => EthereumEpochsRoute,
} as any)
const EthereumEntitiesEntityRoute = EthereumEntitiesEntityRouteImport.update({
  id: '/$entity',
  path: '/$entity',
  getParentRoute: () => EthereumEntitiesRoute,
} as any)
const EthereumDataAvailabilityCustodyRoute =
  EthereumDataAvailabilityCustodyRouteImport.update({
    id: '/custody',
    path: '/custody',
    getParentRoute: () => EthereumDataAvailabilityRoute,
  } as any)
const EthereumDataAvailabilityCustodyIndexRoute =
  EthereumDataAvailabilityCustodyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EthereumDataAvailabilityCustodyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ethereum': typeof EthereumRouteWithChildren
  '/experiments': typeof ExperimentsRouteWithChildren
  '/xatu': typeof XatuRouteWithChildren
  '/beacon/locally-built-blocks': typeof BeaconLocallyBuiltBlocksRoute
  '/ethereum/data-availability': typeof EthereumDataAvailabilityRouteWithChildren
  '/ethereum/entities': typeof EthereumEntitiesRouteWithChildren
  '/ethereum/epochs': typeof EthereumEpochsRouteWithChildren
  '/ethereum/live': typeof EthereumLiveRoute
  '/ethereum/slots': typeof EthereumSlotsRouteWithChildren
  '/experiments/block-production-flow': typeof ExperimentsBlockProductionFlowRoute
  '/experiments/live-slots': typeof ExperimentsLiveSlotsRoute
  '/xatu-data/fork-readiness': typeof XatuDataForkReadinessRoute
  '/xatu-data/geographical-checklist': typeof XatuDataGeographicalChecklistRoute
  '/xatu/contributors': typeof XatuContributorsRouteWithChildren
  '/xatu/fork-readiness': typeof XatuForkReadinessRoute
  '/xatu/geographical-checklist': typeof XatuGeographicalChecklistRoute
  '/xatu/locally-built-blocks': typeof XatuLocallyBuiltBlocksRoute
  '/experiments/': typeof ExperimentsIndexRoute
  '/xatu-data': typeof XatuDataIndexRoute
  '/ethereum/data-availability/custody': typeof EthereumDataAvailabilityCustodyRouteWithChildren
  '/ethereum/entities/$entity': typeof EthereumEntitiesEntityRoute
  '/ethereum/epochs/$epoch': typeof EthereumEpochsEpochRoute
  '/ethereum/slots/$slot': typeof EthereumSlotsSlotRoute
  '/xatu/contributors/$id': typeof XatuContributorsIdRoute
  '/ethereum/entities/': typeof EthereumEntitiesIndexRoute
  '/ethereum/epochs/': typeof EthereumEpochsIndexRoute
  '/ethereum/slots/': typeof EthereumSlotsIndexRoute
  '/xatu/contributors/': typeof XatuContributorsIndexRoute
  '/ethereum/data-availability/custody/': typeof EthereumDataAvailabilityCustodyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ethereum': typeof EthereumRouteWithChildren
  '/xatu': typeof XatuRouteWithChildren
  '/beacon/locally-built-blocks': typeof BeaconLocallyBuiltBlocksRoute
  '/ethereum/data-availability': typeof EthereumDataAvailabilityRouteWithChildren
  '/ethereum/live': typeof EthereumLiveRoute
  '/experiments/block-production-flow': typeof ExperimentsBlockProductionFlowRoute
  '/experiments/live-slots': typeof ExperimentsLiveSlotsRoute
  '/xatu-data/fork-readiness': typeof XatuDataForkReadinessRoute
  '/xatu-data/geographical-checklist': typeof XatuDataGeographicalChecklistRoute
  '/xatu/fork-readiness': typeof XatuForkReadinessRoute
  '/xatu/geographical-checklist': typeof XatuGeographicalChecklistRoute
  '/xatu/locally-built-blocks': typeof XatuLocallyBuiltBlocksRoute
  '/experiments': typeof ExperimentsIndexRoute
  '/xatu-data': typeof XatuDataIndexRoute
  '/ethereum/entities/$entity': typeof EthereumEntitiesEntityRoute
  '/ethereum/epochs/$epoch': typeof EthereumEpochsEpochRoute
  '/ethereum/slots/$slot': typeof EthereumSlotsSlotRoute
  '/xatu/contributors/$id': typeof XatuContributorsIdRoute
  '/ethereum/entities': typeof EthereumEntitiesIndexRoute
  '/ethereum/epochs': typeof EthereumEpochsIndexRoute
  '/ethereum/slots': typeof EthereumSlotsIndexRoute
  '/xatu/contributors': typeof XatuContributorsIndexRoute
  '/ethereum/data-availability/custody': typeof EthereumDataAvailabilityCustodyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ethereum': typeof EthereumRouteWithChildren
  '/experiments': typeof ExperimentsRouteWithChildren
  '/xatu': typeof XatuRouteWithChildren
  '/beacon/locally-built-blocks': typeof BeaconLocallyBuiltBlocksRoute
  '/ethereum/data-availability': typeof EthereumDataAvailabilityRouteWithChildren
  '/ethereum/entities': typeof EthereumEntitiesRouteWithChildren
  '/ethereum/epochs': typeof EthereumEpochsRouteWithChildren
  '/ethereum/live': typeof EthereumLiveRoute
  '/ethereum/slots': typeof EthereumSlotsRouteWithChildren
  '/experiments/block-production-flow': typeof ExperimentsBlockProductionFlowRoute
  '/experiments/live-slots': typeof ExperimentsLiveSlotsRoute
  '/xatu-data/fork-readiness': typeof XatuDataForkReadinessRoute
  '/xatu-data/geographical-checklist': typeof XatuDataGeographicalChecklistRoute
  '/xatu/contributors': typeof XatuContributorsRouteWithChildren
  '/xatu/fork-readiness': typeof XatuForkReadinessRoute
  '/xatu/geographical-checklist': typeof XatuGeographicalChecklistRoute
  '/xatu/locally-built-blocks': typeof XatuLocallyBuiltBlocksRoute
  '/experiments/': typeof ExperimentsIndexRoute
  '/xatu-data/': typeof XatuDataIndexRoute
  '/ethereum/data-availability/custody': typeof EthereumDataAvailabilityCustodyRouteWithChildren
  '/ethereum/entities/$entity': typeof EthereumEntitiesEntityRoute
  '/ethereum/epochs/$epoch': typeof EthereumEpochsEpochRoute
  '/ethereum/slots/$slot': typeof EthereumSlotsSlotRoute
  '/xatu/contributors/$id': typeof XatuContributorsIdRoute
  '/ethereum/entities/': typeof EthereumEntitiesIndexRoute
  '/ethereum/epochs/': typeof EthereumEpochsIndexRoute
  '/ethereum/slots/': typeof EthereumSlotsIndexRoute
  '/xatu/contributors/': typeof XatuContributorsIndexRoute
  '/ethereum/data-availability/custody/': typeof EthereumDataAvailabilityCustodyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ethereum'
    | '/experiments'
    | '/xatu'
    | '/beacon/locally-built-blocks'
    | '/ethereum/data-availability'
    | '/ethereum/entities'
    | '/ethereum/epochs'
    | '/ethereum/live'
    | '/ethereum/slots'
    | '/experiments/block-production-flow'
    | '/experiments/live-slots'
    | '/xatu-data/fork-readiness'
    | '/xatu-data/geographical-checklist'
    | '/xatu/contributors'
    | '/xatu/fork-readiness'
    | '/xatu/geographical-checklist'
    | '/xatu/locally-built-blocks'
    | '/experiments/'
    | '/xatu-data'
    | '/ethereum/data-availability/custody'
    | '/ethereum/entities/$entity'
    | '/ethereum/epochs/$epoch'
    | '/ethereum/slots/$slot'
    | '/xatu/contributors/$id'
    | '/ethereum/entities/'
    | '/ethereum/epochs/'
    | '/ethereum/slots/'
    | '/xatu/contributors/'
    | '/ethereum/data-availability/custody/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ethereum'
    | '/xatu'
    | '/beacon/locally-built-blocks'
    | '/ethereum/data-availability'
    | '/ethereum/live'
    | '/experiments/block-production-flow'
    | '/experiments/live-slots'
    | '/xatu-data/fork-readiness'
    | '/xatu-data/geographical-checklist'
    | '/xatu/fork-readiness'
    | '/xatu/geographical-checklist'
    | '/xatu/locally-built-blocks'
    | '/experiments'
    | '/xatu-data'
    | '/ethereum/entities/$entity'
    | '/ethereum/epochs/$epoch'
    | '/ethereum/slots/$slot'
    | '/xatu/contributors/$id'
    | '/ethereum/entities'
    | '/ethereum/epochs'
    | '/ethereum/slots'
    | '/xatu/contributors'
    | '/ethereum/data-availability/custody'
  id:
    | '__root__'
    | '/'
    | '/ethereum'
    | '/experiments'
    | '/xatu'
    | '/beacon/locally-built-blocks'
    | '/ethereum/data-availability'
    | '/ethereum/entities'
    | '/ethereum/epochs'
    | '/ethereum/live'
    | '/ethereum/slots'
    | '/experiments/block-production-flow'
    | '/experiments/live-slots'
    | '/xatu-data/fork-readiness'
    | '/xatu-data/geographical-checklist'
    | '/xatu/contributors'
    | '/xatu/fork-readiness'
    | '/xatu/geographical-checklist'
    | '/xatu/locally-built-blocks'
    | '/experiments/'
    | '/xatu-data/'
    | '/ethereum/data-availability/custody'
    | '/ethereum/entities/$entity'
    | '/ethereum/epochs/$epoch'
    | '/ethereum/slots/$slot'
    | '/xatu/contributors/$id'
    | '/ethereum/entities/'
    | '/ethereum/epochs/'
    | '/ethereum/slots/'
    | '/xatu/contributors/'
    | '/ethereum/data-availability/custody/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EthereumRoute: typeof EthereumRouteWithChildren
  ExperimentsRoute: typeof ExperimentsRouteWithChildren
  XatuRoute: typeof XatuRouteWithChildren
  BeaconLocallyBuiltBlocksRoute: typeof BeaconLocallyBuiltBlocksRoute
  XatuDataForkReadinessRoute: typeof XatuDataForkReadinessRoute
  XatuDataGeographicalChecklistRoute: typeof XatuDataGeographicalChecklistRoute
  XatuDataIndexRoute: typeof XatuDataIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xatu': {
      id: '/xatu'
      path: '/xatu'
      fullPath: '/xatu'
      preLoaderRoute: typeof XatuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethereum': {
      id: '/ethereum'
      path: '/ethereum'
      fullPath: '/ethereum'
      preLoaderRoute: typeof EthereumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xatu-data/': {
      id: '/xatu-data/'
      path: '/xatu-data'
      fullPath: '/xatu-data'
      preLoaderRoute: typeof XatuDataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/': {
      id: '/experiments/'
      path: '/'
      fullPath: '/experiments/'
      preLoaderRoute: typeof ExperimentsIndexRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/xatu/locally-built-blocks': {
      id: '/xatu/locally-built-blocks'
      path: '/locally-built-blocks'
      fullPath: '/xatu/locally-built-blocks'
      preLoaderRoute: typeof XatuLocallyBuiltBlocksRouteImport
      parentRoute: typeof XatuRoute
    }
    '/xatu/geographical-checklist': {
      id: '/xatu/geographical-checklist'
      path: '/geographical-checklist'
      fullPath: '/xatu/geographical-checklist'
      preLoaderRoute: typeof XatuGeographicalChecklistRouteImport
      parentRoute: typeof XatuRoute
    }
    '/xatu/fork-readiness': {
      id: '/xatu/fork-readiness'
      path: '/fork-readiness'
      fullPath: '/xatu/fork-readiness'
      preLoaderRoute: typeof XatuForkReadinessRouteImport
      parentRoute: typeof XatuRoute
    }
    '/xatu/contributors': {
      id: '/xatu/contributors'
      path: '/contributors'
      fullPath: '/xatu/contributors'
      preLoaderRoute: typeof XatuContributorsRouteImport
      parentRoute: typeof XatuRoute
    }
    '/xatu-data/geographical-checklist': {
      id: '/xatu-data/geographical-checklist'
      path: '/xatu-data/geographical-checklist'
      fullPath: '/xatu-data/geographical-checklist'
      preLoaderRoute: typeof XatuDataGeographicalChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xatu-data/fork-readiness': {
      id: '/xatu-data/fork-readiness'
      path: '/xatu-data/fork-readiness'
      fullPath: '/xatu-data/fork-readiness'
      preLoaderRoute: typeof XatuDataForkReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/live-slots': {
      id: '/experiments/live-slots'
      path: '/live-slots'
      fullPath: '/experiments/live-slots'
      preLoaderRoute: typeof ExperimentsLiveSlotsRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/experiments/block-production-flow': {
      id: '/experiments/block-production-flow'
      path: '/block-production-flow'
      fullPath: '/experiments/block-production-flow'
      preLoaderRoute: typeof ExperimentsBlockProductionFlowRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/ethereum/slots': {
      id: '/ethereum/slots'
      path: '/slots'
      fullPath: '/ethereum/slots'
      preLoaderRoute: typeof EthereumSlotsRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/ethereum/live': {
      id: '/ethereum/live'
      path: '/live'
      fullPath: '/ethereum/live'
      preLoaderRoute: typeof EthereumLiveRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/ethereum/epochs': {
      id: '/ethereum/epochs'
      path: '/epochs'
      fullPath: '/ethereum/epochs'
      preLoaderRoute: typeof EthereumEpochsRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/ethereum/entities': {
      id: '/ethereum/entities'
      path: '/entities'
      fullPath: '/ethereum/entities'
      preLoaderRoute: typeof EthereumEntitiesRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/ethereum/data-availability': {
      id: '/ethereum/data-availability'
      path: '/data-availability'
      fullPath: '/ethereum/data-availability'
      preLoaderRoute: typeof EthereumDataAvailabilityRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/beacon/locally-built-blocks': {
      id: '/beacon/locally-built-blocks'
      path: '/beacon/locally-built-blocks'
      fullPath: '/beacon/locally-built-blocks'
      preLoaderRoute: typeof BeaconLocallyBuiltBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xatu/contributors/': {
      id: '/xatu/contributors/'
      path: '/'
      fullPath: '/xatu/contributors/'
      preLoaderRoute: typeof XatuContributorsIndexRouteImport
      parentRoute: typeof XatuContributorsRoute
    }
    '/ethereum/slots/': {
      id: '/ethereum/slots/'
      path: '/'
      fullPath: '/ethereum/slots/'
      preLoaderRoute: typeof EthereumSlotsIndexRouteImport
      parentRoute: typeof EthereumSlotsRoute
    }
    '/ethereum/epochs/': {
      id: '/ethereum/epochs/'
      path: '/'
      fullPath: '/ethereum/epochs/'
      preLoaderRoute: typeof EthereumEpochsIndexRouteImport
      parentRoute: typeof EthereumEpochsRoute
    }
    '/ethereum/entities/': {
      id: '/ethereum/entities/'
      path: '/'
      fullPath: '/ethereum/entities/'
      preLoaderRoute: typeof EthereumEntitiesIndexRouteImport
      parentRoute: typeof EthereumEntitiesRoute
    }
    '/xatu/contributors/$id': {
      id: '/xatu/contributors/$id'
      path: '/$id'
      fullPath: '/xatu/contributors/$id'
      preLoaderRoute: typeof XatuContributorsIdRouteImport
      parentRoute: typeof XatuContributorsRoute
    }
    '/ethereum/slots/$slot': {
      id: '/ethereum/slots/$slot'
      path: '/$slot'
      fullPath: '/ethereum/slots/$slot'
      preLoaderRoute: typeof EthereumSlotsSlotRouteImport
      parentRoute: typeof EthereumSlotsRoute
    }
    '/ethereum/epochs/$epoch': {
      id: '/ethereum/epochs/$epoch'
      path: '/$epoch'
      fullPath: '/ethereum/epochs/$epoch'
      preLoaderRoute: typeof EthereumEpochsEpochRouteImport
      parentRoute: typeof EthereumEpochsRoute
    }
    '/ethereum/entities/$entity': {
      id: '/ethereum/entities/$entity'
      path: '/$entity'
      fullPath: '/ethereum/entities/$entity'
      preLoaderRoute: typeof EthereumEntitiesEntityRouteImport
      parentRoute: typeof EthereumEntitiesRoute
    }
    '/ethereum/data-availability/custody': {
      id: '/ethereum/data-availability/custody'
      path: '/custody'
      fullPath: '/ethereum/data-availability/custody'
      preLoaderRoute: typeof EthereumDataAvailabilityCustodyRouteImport
      parentRoute: typeof EthereumDataAvailabilityRoute
    }
    '/ethereum/data-availability/custody/': {
      id: '/ethereum/data-availability/custody/'
      path: '/'
      fullPath: '/ethereum/data-availability/custody/'
      preLoaderRoute: typeof EthereumDataAvailabilityCustodyIndexRouteImport
      parentRoute: typeof EthereumDataAvailabilityCustodyRoute
    }
  }
}

interface EthereumDataAvailabilityCustodyRouteChildren {
  EthereumDataAvailabilityCustodyIndexRoute: typeof EthereumDataAvailabilityCustodyIndexRoute
}

const EthereumDataAvailabilityCustodyRouteChildren: EthereumDataAvailabilityCustodyRouteChildren =
  {
    EthereumDataAvailabilityCustodyIndexRoute:
      EthereumDataAvailabilityCustodyIndexRoute,
  }

const EthereumDataAvailabilityCustodyRouteWithChildren =
  EthereumDataAvailabilityCustodyRoute._addFileChildren(
    EthereumDataAvailabilityCustodyRouteChildren,
  )

interface EthereumDataAvailabilityRouteChildren {
  EthereumDataAvailabilityCustodyRoute: typeof EthereumDataAvailabilityCustodyRouteWithChildren
}

const EthereumDataAvailabilityRouteChildren: EthereumDataAvailabilityRouteChildren =
  {
    EthereumDataAvailabilityCustodyRoute:
      EthereumDataAvailabilityCustodyRouteWithChildren,
  }

const EthereumDataAvailabilityRouteWithChildren =
  EthereumDataAvailabilityRoute._addFileChildren(
    EthereumDataAvailabilityRouteChildren,
  )

interface EthereumEntitiesRouteChildren {
  EthereumEntitiesEntityRoute: typeof EthereumEntitiesEntityRoute
  EthereumEntitiesIndexRoute: typeof EthereumEntitiesIndexRoute
}

const EthereumEntitiesRouteChildren: EthereumEntitiesRouteChildren = {
  EthereumEntitiesEntityRoute: EthereumEntitiesEntityRoute,
  EthereumEntitiesIndexRoute: EthereumEntitiesIndexRoute,
}

const EthereumEntitiesRouteWithChildren =
  EthereumEntitiesRoute._addFileChildren(EthereumEntitiesRouteChildren)

interface EthereumEpochsRouteChildren {
  EthereumEpochsEpochRoute: typeof EthereumEpochsEpochRoute
  EthereumEpochsIndexRoute: typeof EthereumEpochsIndexRoute
}

const EthereumEpochsRouteChildren: EthereumEpochsRouteChildren = {
  EthereumEpochsEpochRoute: EthereumEpochsEpochRoute,
  EthereumEpochsIndexRoute: EthereumEpochsIndexRoute,
}

const EthereumEpochsRouteWithChildren = EthereumEpochsRoute._addFileChildren(
  EthereumEpochsRouteChildren,
)

interface EthereumSlotsRouteChildren {
  EthereumSlotsSlotRoute: typeof EthereumSlotsSlotRoute
  EthereumSlotsIndexRoute: typeof EthereumSlotsIndexRoute
}

const EthereumSlotsRouteChildren: EthereumSlotsRouteChildren = {
  EthereumSlotsSlotRoute: EthereumSlotsSlotRoute,
  EthereumSlotsIndexRoute: EthereumSlotsIndexRoute,
}

const EthereumSlotsRouteWithChildren = EthereumSlotsRoute._addFileChildren(
  EthereumSlotsRouteChildren,
)

interface EthereumRouteChildren {
  EthereumDataAvailabilityRoute: typeof EthereumDataAvailabilityRouteWithChildren
  EthereumEntitiesRoute: typeof EthereumEntitiesRouteWithChildren
  EthereumEpochsRoute: typeof EthereumEpochsRouteWithChildren
  EthereumLiveRoute: typeof EthereumLiveRoute
  EthereumSlotsRoute: typeof EthereumSlotsRouteWithChildren
}

const EthereumRouteChildren: EthereumRouteChildren = {
  EthereumDataAvailabilityRoute: EthereumDataAvailabilityRouteWithChildren,
  EthereumEntitiesRoute: EthereumEntitiesRouteWithChildren,
  EthereumEpochsRoute: EthereumEpochsRouteWithChildren,
  EthereumLiveRoute: EthereumLiveRoute,
  EthereumSlotsRoute: EthereumSlotsRouteWithChildren,
}

const EthereumRouteWithChildren = EthereumRoute._addFileChildren(
  EthereumRouteChildren,
)

interface ExperimentsRouteChildren {
  ExperimentsBlockProductionFlowRoute: typeof ExperimentsBlockProductionFlowRoute
  ExperimentsLiveSlotsRoute: typeof ExperimentsLiveSlotsRoute
  ExperimentsIndexRoute: typeof ExperimentsIndexRoute
}

const ExperimentsRouteChildren: ExperimentsRouteChildren = {
  ExperimentsBlockProductionFlowRoute: ExperimentsBlockProductionFlowRoute,
  ExperimentsLiveSlotsRoute: ExperimentsLiveSlotsRoute,
  ExperimentsIndexRoute: ExperimentsIndexRoute,
}

const ExperimentsRouteWithChildren = ExperimentsRoute._addFileChildren(
  ExperimentsRouteChildren,
)

interface XatuContributorsRouteChildren {
  XatuContributorsIdRoute: typeof XatuContributorsIdRoute
  XatuContributorsIndexRoute: typeof XatuContributorsIndexRoute
}

const XatuContributorsRouteChildren: XatuContributorsRouteChildren = {
  XatuContributorsIdRoute: XatuContributorsIdRoute,
  XatuContributorsIndexRoute: XatuContributorsIndexRoute,
}

const XatuContributorsRouteWithChildren =
  XatuContributorsRoute._addFileChildren(XatuContributorsRouteChildren)

interface XatuRouteChildren {
  XatuContributorsRoute: typeof XatuContributorsRouteWithChildren
  XatuForkReadinessRoute: typeof XatuForkReadinessRoute
  XatuGeographicalChecklistRoute: typeof XatuGeographicalChecklistRoute
  XatuLocallyBuiltBlocksRoute: typeof XatuLocallyBuiltBlocksRoute
}

const XatuRouteChildren: XatuRouteChildren = {
  XatuContributorsRoute: XatuContributorsRouteWithChildren,
  XatuForkReadinessRoute: XatuForkReadinessRoute,
  XatuGeographicalChecklistRoute: XatuGeographicalChecklistRoute,
  XatuLocallyBuiltBlocksRoute: XatuLocallyBuiltBlocksRoute,
}

const XatuRouteWithChildren = XatuRoute._addFileChildren(XatuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EthereumRoute: EthereumRouteWithChildren,
  ExperimentsRoute: ExperimentsRouteWithChildren,
  XatuRoute: XatuRouteWithChildren,
  BeaconLocallyBuiltBlocksRoute: BeaconLocallyBuiltBlocksRoute,
  XatuDataForkReadinessRoute: XatuDataForkReadinessRoute,
  XatuDataGeographicalChecklistRoute: XatuDataGeographicalChecklistRoute,
  XatuDataIndexRoute: XatuDataIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
