# API service configuration

# Log level
logLevel: "info"

# HTTP server configuration
httpServer:
  host: "${API_HOST}"
  port: ${API_PORT}
  pathPrefix: "lab-data"
  corsAllowAll: true
  allowedOrigins: []

# SRV client configuration
srvClient:
  address: "${SRV_ADDRESS}"

# Cache configuration
cache:
  type: "redis"
  config:
    url: "${REDIS_URL}"
    defaultTTL: 60

# S3 storage configuration
storage:
  endpoint: "${S3_ENDPOINT}"
  region: "${S3_REGION}"
  bucket: "${S3_BUCKET}"
  accessKey: "${S3_ACCESS_KEY}"
  secretKey: "${S3_SECRET_KEY}"
  secure: false
  usePathStyle: true