# Server (SRV) service configuration
logLevel: "debug"

# GRPC server configuration
grpc:
  host: "0.0.0.0"
  port: 6666

# S3 storage configuration
storage:
  endpoint: "${S3_ENDPOINT}"
  region: "${S3_REGION}"
  bucket: "${S3_BUCKET}"
  accessKey: "${S3_ACCESS_KEY}"
  secretKey: "${S3_SECRET_KEY}"
  secure: false
  usePathStyle: true

# Cache configuration
cache:
  type: "redis"
  config:
    url: "${REDIS_URL}"
    defaultTTL: 60

geolocation:
  enabled: ${GEOLOCATION_ENABLED}
  databaseLocation: "${GEOLOCATION_DATABASE_LOCATION}"

# Cartographoor configuration
cartographoor:
  refresh_interval: "1h"
  request_timeout: "30s"
  cache_ttl: "10m"

# Xatu CBT datasource configuration
xatu_cbt:
  cache_ttl: "60s"
  max_query_limit: 1000
  default_limit: 100
  network_configs:
    mainnet:
      enabled: true
      genesisTime: "2020-12-01T12:00:23Z"
      clickhouse:
        dsn: "${XATU_CBT_CLICKHOUSE_URL}"
        insecure_skip_verify: false
      raw_clickhouse:  # Raw xatu access (for non-CBT tables)
        dsn: "${XATU_CLICKHOUSE_URL}"
        protocol: "native"
    sepolia:
      enabled: true
      genesisTime: "2022-06-20T12:00:00Z"
      clickhouse:
        dsn: "${XATU_CBT_CLICKHOUSE_URL}"
        insecure_skip_verify: false
      raw_clickhouse: # Raw xatu access (for non-CBT tables)
        dsn: "${XATU_CLICKHOUSE_URL}"
        protocol: "native"
    hoodi:
      enabled: true
      genesisTime: "2025-03-17T12:10:00Z"
      clickhouse:
        dsn: "${XATU_CBT_CLICKHOUSE_URL}"
        insecure_skip_verify: false
      raw_clickhouse:  # Raw xatu access (for non-CBT tables)
        dsn: "${XATU_CLICKHOUSE_URL}"
        protocol: "native"

# Experiments configuration
experiments:
  - id: "contributoors"
    enabled: true
    networks: [ "mainnet", "hoodi", "sepolia" ]
  - id: "live-slots"
    enabled: true
    networks: ["mainnet", "hoodi"]
    config:
      head_delay_slots: 2
      backfill_slots: 1000
  - id: "block-production-flow"
    enabled: true
    networks: ["mainnet", "hoodi"]
    config:
      head_delay_slots: 2
      backfill_slots: 1000
  - id: "historical-slots"
    enabled: true
    networks: ["mainnet", "hoodi"]
    config:
      head_delay_slots: 2
      backfill_slots: 1000
  - id: "locally-built-blocks"
    enabled: true
    networks: ["mainnet", "hoodi"]
    config:
      slots: 16
      ttl: "6h"

