---
name: Run Notebooks

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Manual trigger
  
jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install papermill pyyaml
          
      - name: Run notebooks
        env:
          # Add any required environment variables here
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd notebooks
          for notebook in *.ipynb; do
            if [ -f "$notebook" ]; then
              echo "Running $notebook"
              python ../notebook_runner.py "$notebook"
            fi
          done
          
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Commit and push changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add data/ ui/data/
            git commit -m "chore: update notebook data [skip ci]"
            
            # Try to push, if fails due to remote changes, rebase and try again
            if ! git push; then
              git pull --rebase
              git push
            fi
          else
            echo "No changes to commit"
          fi 